name: Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: false
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      RELEASE: ${{ inputs.tag != '' && inputs.tag || github.ref_name }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ env.RELEASE }}
      - uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Build
        run: |
          TARGET_ARCH=("amd64" "arm64")
          TARGET_OS=("linux" "darwin" "windows")
          for arch in "${TARGET_ARCH[@]}"; do
            for os in "${TARGET_OS[@]}"; do
              GOOS="$os" GOARCH="$arch" go build -o odin-"$os"-"$arch" ./cmd/odin
            done
          done
      - name: Upload Builds
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload "$RELEASE" odin-*-*